aprs:
  callsign: 'UR5WKM-10'
  host: "rotate.aprs2.net"
  filter: "-p/A/B/C/D/E/F/G/H/I/J/K/L/M/N/O/P/Q/R/S/T/V/W/X/Y/Z/UA/UB/UC/UD/UE/UF/UG/UH/UI/UJ/UK/UL/UM/UN/UO/UP/UQ r/49.7/25.35/284 r/49.44/31.5/368 r/48.81/37.79/202 r/47/32.46/388"

logging:
  # Allowed levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: 'INFO'

mysql:
  hostname: 'localhost'
  unix_socket: '/run/mysqld/mysqld.sock'
  username: 'root'
  password: 'a'
  database: 'aprs_statuses'